[theme]
base = "dark"

# General color setup
textColor = "#e2e8f0"
primaryColor = "#615fff"
backgroundColor = "#0E1626"
secondaryBackgroundColor = "#111827"

# Widgets
showWidgetBorder = true
borderColor = "#1f2937"

# Dataframes
dataframeHeaderBackgroundColor = "#111827"

# Base text
font = "'Space Grotesk':https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300..700&display=swap"
baseFontWeight = 300
baseFontSize = 14

# Heading text
headingFont = "Space Grotesk"
headingFontWeights = [300, 400, 400, 300, 300, 300]
headingFontSizes = ["2.5rem", "1.5rem", "1rem"]
